### ISSUE TITLE
Add Watson Services

### ISSUE THREAD

**Issue by mediumTaj** [mediumTaj/unity-sdk-demo-classification#4]
Add 
- [x] Speech to Text
- [x] Natural Language Classification or Conversation
- [x] Text to Speech
